name: Deplay project
on: [push,workflow_dispatch]
jobs:
  test: # name of the job
   runs-on: ubuntu-latest
   steps:
     - name: Get code
       uses: actions/checkout@v4 #an action already made by github to checkout a branch
     - name: Install nodejs
       uses: actions/setup-node@v3
       with:
        node-version: 18
     - name: install depensencies
       run: npm ci #install all the dependecies which are locked in package-lock.jason
     - name: run test
       run: npm test
  deplay:
   needs: test #also we can wait for multiple jobs to finish by syntax [test,job2]
   runs-on: ubuntu-latest
   steps:
     - name: Get code
       uses: actions/checkout@v4 #an action already made by github to checkout a branch
     - name: Install nodejs
       uses: actions/setup-node@v3
       with:
        node-version: 18
     - name: install depensencies
       run: npm ci
     - name: build project
       run: npm run build
     - name: Deplay
       run: echo "Deplaying..."

